```{r}
library(ggplot2)
library(GGally)
library(DESeq2)
library(ggbeeswarm)
library(haven)
library(readxl)
library(dplyr)
library(patchwork)
library(tidyverse)


#!!!File import/Prep!!!
csv_meta <- read.csv("/restricted/projectnb/cteseq/projects/CTE_data_processing/all_meta.csv")
counts <- read.csv("/restricted/projectnb/cteseq/projects/CTE_data_processing/all_counts.csv")
AT8_ex_data <- read.csv("/restricted/projectnb/cteseq/jrose/cte_DLFCWSAT8.csv")[ ,2:3]
cte_missing_data <- read_excel("/restricted/projectnb/cteseq/projects/CTE_data_processing/09.28.2023_dataset/CTE CASES FOR MISSING APOE AND TMEM.xlsx")
sav_meta <- read_sav("/restricted/projectnb/cteseq/jrose/RNAsequence.sav")
#Fixes a mismatched sample name
sav_meta$subjid <- gsub("BVAX81", "BVAX081", sav_meta$subjid)
#Changes format to match other rs value
sav_meta$rs3173615 <- gsub("C", "C:C", sav_meta$rs3173615)
sav_meta$rs3173615 <- gsub("G", "G:G", sav_meta$rs3173615)
sav_meta$rs3173615 <- gsub("C:CG:G", "C:G", sav_meta$rs3173615)
#renamed for ease of merging
colnames(cte_missing_data)[1] = "subjid"
colnames(cte_missing_data)[2] = "apoe"
colnames(cte_missing_data)[3] = "rs3173615"
#Merge cte_missing_data into spss_meta file.
sav_meta <- merge(sav_meta, cte_missing_data, by = "subjid", all.x = TRUE)
sav_meta$rs3173615 <- ifelse(sav_meta$rs3173615.x == "" & sav_meta$rs3173615.y != "", sav_meta$rs3173615.y, sav_meta$rs3173615.x)
sav_meta$apoe <- ifelse(is.na(sav_meta$apoe.x) & sav_meta$apoe.y != "", sav_meta$apoe.y, sav_meta$apoe.x)
sav_meta <- subset(sav_meta, select = -c(apoe.x, apoe.y, rs3173615.x, rs3173615.y))
#Merge in additional AT8 data
AT8_ex_data$subjid <- gsub("K", "K-", AT8_ex_data$subjid)
AT8_ex_data$subjid <- gsub("SLI", "SLI-", AT8_ex_data$subjid)
AT8_ex_data$subjid <- gsub("SLI-0", "SLI-", AT8_ex_data$subjid)
sav_merged <- merge(sav_meta, AT8_ex_data, by = "subjid")



#!!!Counts!!!
#Sets counts gene names (X) to row names, then removing that column
rownames(counts) <- counts$X
counts <- subset(counts, select = -X)
#Filters out gene names that have 150 or more zeros
filter_metric <- rowSums(counts == 0) < 150
#filter_metric <- rowSums(counts >= 10)
filtered_counts <- counts[filter_metric,]
#Sorts column names alphabetically for deseq
filtered_counts <- filtered_counts[, order(names(filtered_counts))]



#!!!Creating merged meta file and transforming data!!!
#substitutes K values with only 3 digits after "K-" to have a 0 in front of them
csv_meta$Sample_ID <- gsub("^K-(\\d{3})", "K-0\\1", csv_meta$Sample_ID)
#Does the same as above, but for SampleName instead of Sample_ID.
csv_meta$SampleName <- gsub("^K-(\\d{3}$)", "K-0\\1", csv_meta$SampleName)
#changes Corde_ID in CSV to line up with counts file. Example: ST_AN_K-688 to ST_AN_K.688
csv_meta$Core_ID <- gsub("^ST_AN_K-", "ST_AN_K.", csv_meta$Core_ID)
csv_meta$Core_ID <- gsub("^ST_AN_SLI-", "ST_AN_SLI.", csv_meta$Core_ID)
#Changing the value of 7 to NA in npbraak. It seems odd with a continuous model and only has one person
sav_merged$npbraak <- gsub("7", NA, sav_merged$npbraak)
#Merges meta data files. 
csv_meta <- csv_meta[,c("SampleName", "RIN", "Core_ID", "Batch", "Year")]
merged_meta <- merge(csv_meta, sav_merged, by.x = "SampleName", by.y = "subjid")
#Transforming apoe, Group/CTE and tmem
merged_meta$DLFC.WS.AT8..cell.mm2 <- gsub("#N/A", NA, merged_meta$DLFC.WS.AT8..cell.mm2)
merged_meta$Group_de <- ifelse(merged_meta$Group %in% c(1,2), "low", ifelse(merged_meta$Group == 3, "high", NA))
merged_meta$apoe_de <- ifelse(merged_meta$apoe %in% c(24, 34, 44), 1, 0)
merged_meta$apoe_de <- ifelse(merged_meta$apoe %in% c(24, 34, 44), 1, 0)
merged_meta$TMEM106B_dom <- ifelse(merged_meta$rs3173615 %in% c("C:C", "C:G"), 1, ifelse(merged_meta$rs3173615 == "G:G", 0, NA))
merged_meta$TMEM106B_invrec <- ifelse(merged_meta$rs3173615 == "C:C", 1, ifelse(merged_meta$rs3173615 %in% c("G:G", "C:G"), 0, NA))
#Sorts Core_ID alphabetically
merged_meta <- merged_meta[order(merged_meta[["Core_ID"]]), ]
#Sets Core_ID to row names for deseq2 #rownames(merged_meta) <- merged_meta$Core_ID
#AT8log
merged_meta$AT8sulcusLog <- log(merged_meta$AT8sulcus)
merged_meta$AT8crestLog <- log(merged_meta$AT8crest)



#!!!Filtering meta file!!!
#Turns AT8 Extra data into numeric instead of characters
merged_meta$DLFC.WS.AT8..cell.mm2 <- as.numeric(merged_meta$DLFC.WS.AT8..cell.mm2)
merged_meta$AT8_total <- merged_meta$DLFC.WS.AT8..cell.mm2
merged_meta <- subset(merged_meta, select = -c(DLFC.WS.AT8..cell.mm2))
#rearrange factor levels. Only binary category to have reversed factors by default. Others are fine
merged_meta$Group_de <- factor(merged_meta$Group_de, levels = c("low", "high"))
merged_meta$Batch <- as.factor(merged_meta$Batch)
merged_meta$Year<- as.factor(merged_meta$Year)
#merged_meta['agedeath'] <- scale(merged_meta['agedeath'])
#merged_meta['RIN'] <- scale(merged_meta['RIN'])
#merged_meta['AT8_total'] <- scale(merged_meta['AT8_total'])


scale_cols <- c('agedeath', 'RIN', 'AT8_total')
merged_meta[scale_cols] <- scale(merged_meta[scale_cols])


#scale_cols <- num_cols[lapply(f[num_cols], function(x){mean(x, na.rm=T)})>5]
#f[scale_cols] <- lapply(f[scale_cols], function(x){scale(x,center=T, scale=T)[1:length(x)]})

#Filtering out NA values on set design columns
merged_meta <- subset(merged_meta, !is.na(merged_meta$agedeath))
merged_meta <- subset(merged_meta, !is.na(merged_meta$RIN))
merged_meta <- subset(merged_meta, !is.na(merged_meta$AT8_total))
#Filtering counts to only contain Core_ID (columns in counts) in the merged_AT8 df
#counts_filtered <- counts[, names(counts) %in% merged_AT8$Core_ID]
rounded <- round(filtered_counts)



#!!!categorizing data columns by type!!!
col_continuous <- c("footyrs", "AFE", "totyrs", "agecogsx", "cogdecage", "mincogage", "disdur", "aestot", "bistot", "tbri", "tmi", "tgec", "maxaggsum", "CDStot", 
                    "chii_f", "chii_g", "faqtot", "GDStot")
col_categorical <- c("DementiaHx", "npold", "nppath", "npftdtau", "PathAD", "PathFTD", "CTE", 
                     "suicide", "Group_de", "apoe_de", "TMEM106B_dom", "TMEM106B_invrec", "ParknismHx", 
                     "nptdpb", "nptdpc", "nptdpe", "csparCTE", "sleepact")

gives_error <- c("chii_r")
col_ordinal <- c("npavas", "npwmr", "npbraak", "npneur", "npadnc", "npdiff", "npamy", "nparter")
col_categorical_polychotomous <- c("PathLBD", "CTEStage", "Group", "cod", "nplbod", "nphipscl")

new_col <- c("aestot", "bistot", "tbri", "tmi", "tgec", "maxaggsum", "CDStot", "chii_f", "chii_r", 
             "chii_g", "ParknismHx", "faqtot", "GDStot", "nphipscl", "nptdpb", "nptdpc", "nptdpe", 
             "csparCTE", "sleepcb", "sleepact")
col_exclude <- c("SampleName", "RIN", "Core_ID", "race", "nphemo", "npold1", "npold2", "npold3", "npold4",
                 "npoldd1", "npoldd2", "npoldd3", "npoldd4", "nppath6", "nppick", "npftdt2", "npcort", 
                 "npprog", "npftdt5", "npftdt8", "npftdt9", "npftdt10", "npftdtdp", "micdorfront", "micinfpar", 
                 "micalc", "locratio", "subratio", "CA1ratio", "CA23ratio", "CA4ratio", "sport", "rs1990622", 
                 "rs3173615", "apoe", "PathPrion", "npoftd", "micsuptemp", "PathMND", "AT8sulcus", "AT8crest")
col_combined <- c(col_categorical, col_continuous)


#!!!

for (i in col_categorical) {
  merged_meta[[i]] <- as.factor(merged_meta[[i]])
}


deseq_meta <- merged_meta
deseq_meta_2018 <- merged_meta[!is.na(merged_meta$Year) & merged_meta$Year == 2018, ]
deseq_meta_2021 <- merged_meta[!is.na(merged_meta$Year) & merged_meta$Year == 2021, ]

deseq_meta_group_high <- merged_meta[!is.na(merged_meta$Group_de) & merged_meta$Group_de == "high", ]
deseq_meta_group_low <- merged_meta[!is.na(merged_meta$Group_de) & merged_meta$Group_de == "low", ]

deseq_meta_group_high_2018 <- deseq_meta_group_high[!is.na(deseq_meta_group_high$Year) & deseq_meta_group_high$Year == 2018, ]
deseq_meta_group_high_2021 <- deseq_meta_group_high[!is.na(deseq_meta_group_high$Year) & deseq_meta_group_high$Year == 2021, ]
deseq_meta_group_low_2018 <- deseq_meta_group_low[!is.na(deseq_meta_group_low$Year) & deseq_meta_group_low$Year == 2018, ]
deseq_meta_group_low_2021 <- deseq_meta_group_low[!is.na(deseq_meta_group_low$Year) & deseq_meta_group_low$Year == 2021, ]

deseq_counts <- rounded[, names(rounded) %in% deseq_meta$Core_ID]
saveRDS(deseq_counts, file = "rounded_CTE_counts_for_deconv.rds")
deseq_counts_2018 <- rounded[, names(rounded) %in% deseq_meta_2018$Core_ID]
deseq_counts_2021 <- rounded[, names(rounded) %in% deseq_meta_2021$Core_ID]

deseq_counts_group_high <- rounded[, names(rounded) %in% deseq_meta_group_high$Core_ID]
deseq_counts_group_low <- rounded[, names(rounded) %in% deseq_meta_group_low$Core_ID]

deseq_counts_group_high_2018 <- rounded[, names(rounded) %in% deseq_meta_group_high_2018$Core_ID]
deseq_counts_group_high_2021 <- rounded[, names(rounded) %in% deseq_meta_group_high_2021$Core_ID]
deseq_counts_group_low_2018 <- rounded[, names(rounded) %in% deseq_meta_group_low_2018$Core_ID]
deseq_counts_group_low_2021 <- rounded[, names(rounded) %in% deseq_meta_group_low_2021$Core_ID]
  
design_form_ART <- formula(paste("~ agedeath + RIN + AT8_total"))
design_form_ARTB <- formula(paste("~ agedeath + RIN + Batch + AT8_total"))
design_form_ARTY <- formula(paste("~ agedeath + RIN + Year + AT8_total"))
#design_form_ARTBY <- formula(paste("~ agedeath + RIN + Batch + Year + AT8_total"))





dds_ART <- DESeqDataSetFromMatrix(countData = deseq_counts,
                                  colData = deseq_meta,
                                  design = design_form_ART)
dds_ARTY <- DESeqDataSetFromMatrix(countData = deseq_counts,
                                   colData = deseq_meta,
                                   design = design_form_ARTY)
#dds_ARTBY <- DESeqDataSetFromMatrix(countData = deseq_counts,
#                                    colData = deseq_meta,
#                                    design = design_form_ARTBY)
dds_ARTB <- DESeqDataSetFromMatrix(countData = deseq_counts,
                                  colData = deseq_meta,
                                  design = design_form_ARTB)
dds_ARTB_2018 <- DESeqDataSetFromMatrix(countData = deseq_counts_2018,
                                   colData = deseq_meta_2018,
                                   design = design_form_ARTB)
dds_ARTB_2021 <- DESeqDataSetFromMatrix(countData = deseq_counts_2021,
                                   colData = deseq_meta_2021,
                                   design = design_form_ARTB)

#Group analysis and striation by year
dds_ARTB_group_high <- DESeqDataSetFromMatrix(countData = deseq_counts_group_high,
                                   colData = deseq_meta_group_high,
                                   design = design_form_ARTB)
dds_ARTB_group_low <- DESeqDataSetFromMatrix(countData = deseq_counts_group_low,
                                   colData = deseq_meta_group_low,
                                   design = design_form_ARTB)
dds_ARTB_group_high_2018 <- DESeqDataSetFromMatrix(countData = deseq_counts_group_high_2018,
                                              colData = deseq_meta_group_high_2018,
                                              design = design_form_ARTB)
dds_ARTB_group_high_2021 <- DESeqDataSetFromMatrix(countData = deseq_counts_group_high_2021,
                                              colData = deseq_meta_group_high_2021,
                                              design = design_form_ARTB)
dds_ARTB_group_low_2018 <- DESeqDataSetFromMatrix(countData = deseq_counts_group_low_2018,
                                             colData = deseq_meta_group_low_2018,
                                             design = design_form_ARTB)
dds_ARTB_group_low_2021 <- DESeqDataSetFromMatrix(countData = deseq_counts_group_low_2021,
                                             colData = deseq_meta_group_low_2021,
                                             design = design_form_ARTB)
```

BF591 document ch7
```{r}
vst_ARTY <- vst(dds_ARTY, blind = TRUE)
vst_values <- assay(vst_ARTY)
t_vst_values <- as.data.frame(t(vst_values))
#next line mean centers the data. scale() by default will center by mean and divide by std, but scale=false prevents dividing by std.
vst_centered <- data.frame(lapply(t_vst_values, function(x) scale(x, scale = TRUE)), row.names = row.names(t_vst_values))
pca_result <- prcomp(vst_centered, center = FALSE, scale = FALSE)
pca_res_reduced <- as.data.frame(pca_result$x[, 1:5])
pca_res_reduced$Core_ID <- rownames(pca_res_reduced)

pca_res_merge <- merge(pca_res_reduced, merged_meta, by = "Core_ID")
rownames(pca_res_merge) <- pca_res_merge$Core_ID
pca_res_merge$year_batch <- paste(pca_res_merge$Year, pca_res_merge$Batch, sep="-")


#Section using BF591 instructions on making various visualizations such at scree plots, 
pca_var <- tibble(
  PC=factor(str_c("PC",1:10),str_c("PC",1:10)),
  Variance=pca_result$sdev[1:10]^2,
  `% Explained Variance`=Variance/sum(Variance)*100,
  `Cumulative % Explained Variance`=cumsum(`% Explained Variance`)
)

exp_g <- pca_var %>%
  ggplot(aes(x=PC,y=`% Explained Variance`,group=1)) +
  geom_point() +
  geom_line() +
  theme(axis.text.x=element_text(angle=90,hjust=0,vjust=0.5)) 

cum_g <- pca_var %>%
  ggplot(aes(x=PC,y=`Cumulative % Explained Variance`,group=1)) +
  geom_point() +
  geom_line() +
  ylim(0,100) + 
  theme(axis.text.x=element_text(angle=90,hjust=0,vjust=0.5))

#scree plots
exp_g
cum_g
```

#potential outliers
```{r}

sca_plot_core <- as_tibble(pca_res_merge) %>%
  mutate(type=stringr::str_sub(rownames(pca_res_merge),1,1)) %>%
  ggplot(aes(x=PC1,y=PC2,color=type)) +
  ggtitle("Core ID") +
  geom_point()

sca_plot_year <- as_tibble(pca_res_merge) %>%
  mutate(type=stringr::str_sub(rownames(pca_res_merge),1,1)) %>%
  ggplot(aes(x=PC1,y=PC2,color=pca_res_merge$Year)) +
  ggtitle("Year") +
  geom_point()

sca_plot_stage <- as_tibble(pca_res_merge) %>%
  mutate(type=stringr::str_sub(rownames(pca_res_merge),1,1)) %>%
  ggplot(aes(x=PC1,y=PC2,color=as.factor(pca_res_merge$CTEStage))) +
  ggtitle("CTE Stage") +
  geom_point()

sca_plot_group <- as_tibble(pca_res_merge) %>%
  mutate(type=stringr::str_sub(rownames(pca_res_merge),1,1)) %>%
  ggplot(aes(x=PC1,y=PC2,color=pca_res_merge$Group_de)) +
  ggtitle("CTE Group") +
  geom_point()

sca_plot_AT8 <- as_tibble(pca_res_merge) %>%
  mutate(type=stringr::str_sub(rownames(pca_res_merge),1,1)) %>%
  ggplot(aes(x=PC1,y=PC2,color=pca_res_merge$AT8_total)) +
  ggtitle("AT8 Total") +
  geom_point()

sca_plot_batch <- as_tibble(pca_res_merge) %>%
  mutate(type=stringr::str_sub(rownames(pca_res_merge),1,1)) %>%
  ggplot(aes(x=PC1,y=PC2,color=pca_res_merge$year_batch)) +
  ggtitle("Year-Batch") +
  geom_point()



color_pc_plot <- as_tibble(pca_res_merge) %>%
  mutate(type=stringr::str_sub(rownames(pca_res_merge),1,1)) %>%
  dplyr::select(c(type,PC1:PC5)) %>%
  ggpairs(columns=1:5,mapping=aes(fill=pca_res_merge$Core_ID))


bswarm_plot_core <- as_tibble(pca_res_merge) %>%
  mutate(
    sample=rownames(pca_res_merge),
    type=stringr::str_sub(sample,1,1)
  ) %>%
  pivot_longer(PC1:PC5,names_to="PC",values_to="projection") %>%
  mutate(PC=fct_relevel(PC,str_c("PC",1:5))) %>%
  ggplot(aes(x=PC,y=projection,color=type)) +
  geom_beeswarm() + labs(title="Core ID") +
  theme(axis.text.x=element_text(angle=90,hjust=0,vjust=0.5))

bswarm_plot_year <- as_tibble(pca_res_merge) %>%
  mutate(
    sample=rownames(pca_res_merge),
    type=stringr::str_sub(sample,1,1)
  ) %>%
  pivot_longer(PC1:PC5,names_to="PC",values_to="projection") %>%
  mutate(PC=fct_relevel(PC,str_c("PC",1:5))) %>%
  ggplot(aes(x=PC,y=projection,color=Year)) +
  geom_beeswarm() + labs(title="Year") +
  theme(axis.text.x=element_text(angle=90,hjust=0,vjust=0.5))

bswarm_plot_stage <- as_tibble(pca_res_merge) %>%
  mutate(
    sample=rownames(pca_res_merge),
    type=stringr::str_sub(sample,1,1)
  ) %>%
  pivot_longer(PC1:PC5,names_to="PC",values_to="projection") %>%
  mutate(PC=fct_relevel(PC,str_c("PC",1:5))) %>%
  ggplot(aes(x=PC,y=projection,color=as.factor(CTEStage))) +
  geom_beeswarm() + labs(title="CTE Stage") +
  theme(axis.text.x=element_text(angle=90,hjust=0,vjust=0.5))

bswarm_plot_group <- as_tibble(pca_res_merge) %>%
  mutate(
    sample=rownames(pca_res_merge),
    type=stringr::str_sub(sample,1,1)
  ) %>%
  pivot_longer(PC1:PC5,names_to="PC",values_to="projection") %>%
  mutate(PC=fct_relevel(PC,str_c("PC",1:5))) %>%
  ggplot(aes(x=PC,y=projection,color=Group_de)) +
  geom_beeswarm() + labs(title="Group") +
  theme(axis.text.x=element_text(angle=90,hjust=0,vjust=0.5))

bswarm_plot_AT8 <- as_tibble(pca_res_merge) %>%
  mutate(
    sample=rownames(pca_res_merge),
    type=stringr::str_sub(sample,1,1)
  ) %>%
  pivot_longer(PC1:PC5,names_to="PC",values_to="projection") %>%
  mutate(PC=fct_relevel(PC,str_c("PC",1:5))) %>%
  ggplot(aes(x=PC,y=projection,color=AT8_total)) +
  geom_beeswarm() + labs(title="AT8 Total") +
  theme(axis.text.x=element_text(angle=90,hjust=0,vjust=0.5))

bswarm_plot_batch <- as_tibble(pca_res_merge) %>%
  mutate(
    sample=rownames(pca_res_merge),
    type=stringr::str_sub(sample,1,1)
  ) %>%
  pivot_longer(PC1:PC5,names_to="PC",values_to="projection") %>%
  mutate(PC=fct_relevel(PC,str_c("PC",1:5))) %>%
  ggplot(aes(x=PC,y=projection,color=year_batch)) +
  geom_beeswarm() + labs(title="Year-Batch") +
  theme(axis.text.x=element_text(angle=90,hjust=0,vjust=0.5))


#color_pc_plot


sca_plot_core
sca_plot_year
sca_plot_stage
sca_plot_group
sca_plot_AT8
sca_plot_batch

bswarm_plot_core
bswarm_plot_year
bswarm_plot_stage
bswarm_plot_group
bswarm_plot_AT8
bswarm_plot_batch
```

Clustering
```{r}
#creates elbow plot
wss <- numeric(15)

for (i in 1:15) {
  kmeans_result <- kmeans(pca_result$x, centers = i, nstart = 20)
  wss[i] <- sum(kmeans_result$withinss)
}

plot(1:15, wss, type = "b", pch = 19, frame = FALSE, 
     xlab = "Number of Clusters (k)", ylab = "Within-Cluster Sum of Squares")

#creates clustering results for plotting
kmeans_result <- kmeans(pca_result$x, centers = 4, nstart = 20)


ggplot(data.frame(PC1 = pca_result$x[, 1], PC2 = pca_result$x[, 2], Cluster = factor(kmeans_result$cluster)),
       aes(x = PC1, y = PC2, color = Cluster)) +
  geom_point() +
  labs(title = "K-means Clustering with PCA")




```


