---
title: "Seurat tutorial"
output: 
---

Creating the Seurat object:
```{r}
library(dplyr)
library(Seurat)
library(patchwork)

#loading datasets
counts_data <- read.csv("/restricted/projectnb/cteseq/projects/ALS_rnaseq/data/raw/exp_counts.csv", row.names = 1)
meta_data <- read.csv("/restricted/projectnb/cteseq/projects/ALS_rnaseq/data/raw/exp_meta.csv")
#filter metadata under Primary_Dx for ALS only 
meta_data_filtered <- filter(meta_data, Primary_Dx == "ALS")
meta_data_filtered <- as.data.frame(meta_data_filtered)
rownames(meta_data_filtered) <- meta_data_filtered$Core_ID
#Gets each unique value from the Core_ID column in metadata and assigns it to "sample"
sample <- unique(meta_data_filtered$Core_ID)
#subsets the values from "sample" from the counts data so only ALS data remains
counts_data_filtered <- counts_data[,sample]
#passing counts and meta data to a seurat objext
obj <- CreateSeuratObject(counts = counts_data_filtered, meta.data = meta_data_filtered)
obj
```


```{r}
#QC section of tutorial
#example plots
VlnPlot(obj, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2)
ftplot <- FeatureScatter(obj, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
ftplot
#Filtering step. Based on violin plots, filtered out points with more than 25000 features or less than 33000
obj <- subset(obj, subset = nFeature_RNA > 25000 & nFeature_RNA < 33000)

#Normalizing data
obj <- NormalizeData(obj)
#Identifying most high variable features
obj <- FindVariableFeatures(obj, selection.method = "vst", nFeatures = 5000)
#Plot variable features, displaying without top 10 and with. This working correctly seems...
#...to depend on the computer/server running the code
top10 <- head(VariableFeatures(obj), 10)
fsplot1 <- VariableFeaturePlot(obj)
fsplot2 <- LabelPoints(plot = fsplot1, points = top10, repel = TRUE)
fsplot2 #+ fsplot2
```


```{r}
#Data scaling
all.genes <- rownames(obj)
obj <- ScaleData(obj, features = all.genes)
#Linear dimensional reduction
#runs pca
obj <- RunPCA(obj, features = VariableFeatures(object = obj))
print(obj[["pca"]], dims = 1)
```



```{r}
#plots
VizDimLoadings(obj, dims = 1:2, reduction = "pca")
DimPlot(obj, reduction = "pca")
#heatmaps
DimHeatmap(obj, dims = 1, cells = 500, balanced = TRUE)
DimHeatmap(obj, dims = 1:15, cells = 500, balanced = TRUE)
#dataset dimensionality. JSP shows 13 significant
obj <- JackStraw(obj, num.replicate = 100)
obj <- ScoreJackStraw(obj, dims = 1:15)
JackStrawPlot(obj, dims = 1:15)
ElbowPlot(obj)
#Clustering cells
obj <- FindNeighbors(obj, dims = 1:8)
obj <- FindClusters(obj, resolution = 0.5)
head(Idents(obj),5)
#UMAP/tSNE
obj <- RunUMAP(obj, dims = 1:8)
DimPlot(obj, reduction = "umap")
```









