


```{r, echo=FALSE}
library(DESeq2)
library(dplyr)
library(biomaRt)
library(tidyverse)
library(pheatmap)
library(fgsea)
```

```{r}
synGO_gmt <- gmtPathways("/restricted/projectnb/cteseq/jrose/synGO.gmt")
c2_gmt <- gmtPathways("/restricted/projectnb/cteseq/jrose/c2.cp.v2023.2.Hs.symbols.gmt")


dds_ART<- readRDS("/restricted/projectnb/cteseq/jrose/results/cte_deseq_output_ART_model.rds")
dds_ARTB <- readRDS("/restricted/projectnb/cteseq/jrose/results/cte_deseq_output_ARTB_model.rds")
dds_ARTY <- readRDS("/restricted/projectnb/cteseq/jrose/results/cte_deseq_output_ARTY_model.rds")
#dds_ARTBY <- readRDS("/restricted/projectnb/cteseq/jrose/results/cte_deseq_output_ARTBY_model.rds")
dds_ARTB_2018 <- readRDS("/restricted/projectnb/cteseq/jrose/results/cte_deseq_output_ARTB_2018_model.rds")
dds_ARTB_2021 <- readRDS("/restricted/projectnb/cteseq/jrose/results/cte_deseq_output_ARTB_2021_model.rds")

dds_ARTB_group_high <- readRDS("/restricted/projectnb/cteseq/jrose/results/cte_deseq_output_ARTB_group_high_model.rds")
dds_ARTB_group_low <- readRDS("/restricted/projectnb/cteseq/jrose/results/cte_deseq_output_ARTB_group_low_model.rds")
dds_ARTB_group_high_2018 <- readRDS("/restricted/projectnb/cteseq/jrose/results/cte_deseq_output_ARTB_group_high_2018_model.rds")
dds_ARTB_group_high_2021 <- readRDS("/restricted/projectnb/cteseq/jrose/results/cte_deseq_output_ARTB_group_high_2021_model.rds")
dds_ARTB_group_low_2018 <- readRDS("/restricted/projectnb/cteseq/jrose/results/cte_deseq_output_ARTB_group_low_2018_model.rds")
dds_ARTB_group_low_2021 <- readRDS("/restricted/projectnb/cteseq/jrose/results/cte_deseq_output_ARTB_group_low_2021_model.rds")

dds_list <- list(dds_ART, dds_ARTB, dds_ARTY, dds_ARTB_2018, dds_ARTB_2021, dds_ARTB_group_high, dds_ARTB_group_low, dds_ARTB_group_high_2018, dds_ARTB_group_high_2021, dds_ARTB_group_low_2018, dds_ARTB_group_low_2021)
names(dds_list) <- c("dds_ART", "dds_ARTB", "dds_ARTY", "dds_ARTB_2018", "dds_ARTB_2021", "dds_ARTB_group_high", "dds_ARTB_group_low", "dds_ARTB_group_high_2018", "dds_ARTB_group_high_2021", "dds_ARTB_group_low_2018", "dds_ARTB_group_low_2021")
dds_list_names <- names(dds_list)
```

Create deseq results list and gene mapping
```{r}
dds_list_results <- lapply(
  dds_list_names,
  function(i) {
    dds_res <- results(dds_list[[i]], name = "AT8_total")
    dds_list_df <- data.frame(ENSGID = rownames(dds_res), baseMean = dds_res$baseMean, log2FoldChange = dds_res$log2FoldChange, lfcSE = dds_res$lfcSE, stat = dds_res$stat, pvalue = dds_res$pvalue, padj = dds_res$padj)
    dds_list_df$ENSGID <- sub("\\..*$", "", dds_list_df$ENSGID)
    return(dds_list_df)
  })
names(dds_list_results) <- dds_list_names

#makes vector of ENSGIDs for mapping
ENSG_IDs <- dds_list_results$dds_ART$ENSGID

#Creates a mart object for creating the gene map.
ensembl.con <- useEnsembl(biomart = "genes", dataset = "hsapiens_gene_ensembl")
gene_map <- getBM(attributes = c("ensembl_gene_id", "external_gene_name"),
      filters = "ensembl_gene_id",
      values = ENSG_IDs,
      mart = ensembl.con)

#makes a new column that uses gene symbols unless there is a NA value or no value. In those cases, ENGSID is used instead
dds_list_results_with_symbols <- lapply (
  dds_list_names,
  function(i) {
    dds_with_symbols <- merge(dds_list_results[[i]], gene_map, by.x = "ENSGID", by.y = "ensembl_gene_id", all.x = TRUE)
    dds_with_symbols$all_ID <- ifelse(dds_with_symbols$external_gene_name %in% "" | is.na(dds_with_symbols$external_gene_name), dds_with_symbols$ENSGID, dds_with_symbols$external_gene_name)
    return(dds_with_symbols)
  })
names(dds_list_results_with_symbols) <- dds_list_names

```

Subset sig genes
```{r}
dds_list_results_with_symbols_05 <- lapply (
  dds_list_names,
  function(i) {
    sig_05 <- subset(dds_list_results_with_symbols[[i]], padj < 0.05)
    return(sig_05)
  })
names(dds_list_results_with_symbols_05) <- dds_list_names

dds_list_results_with_symbols_10 <- lapply (
  dds_list_names,
  function(i) {
    sig_10 <- subset(dds_list_results_with_symbols[[i]], padj < 0.1)
    return(sig_10)
  })
names(dds_list_results_with_symbols_10) <- dds_list_names

dds_list_results_with_symbols_25 <- lapply (
  dds_list_names,
  function(i) {
    sig_25 <- subset(dds_list_results_with_symbols[[i]], padj < 0.25)
    return(sig_25)
  })
names(dds_list_results_with_symbols_25) <- dds_list_names

#Create table showing number of sig degs
sig_num <- data.frame( row.names = dds_list_names)
for (i in dds_list_names) {
  sig_num[i, "0.05"] <- nrow(dds_list_results_with_symbols_05[[i]])
  sig_num[i, "0.10"] <- nrow(dds_list_results_with_symbols_10[[i]])
  sig_num[i, "0.25"] <- nrow(dds_list_results_with_symbols_25[[i]])
}

```

ARBT CTE_group High vs. Low
```{r}

#plots for ATB group high vs low
ARTB_high_vs_low_both <- merge(dds_list_results_with_symbols_05$dds_ARTB_group_high, dds_list_results_with_symbols_05$dds_ARTB_group_low, by = "ENSGID")
#Creates a vector of all genes significant in both high/low striations
ARTB_high_vs_low_ENSGID_combined <- unique(c(dds_list_results_with_symbols_05$dds_ARTB_group_low$ENSGID, dds_list_results_with_symbols_05$dds_ARTB_group_high$ENSGID))
#Creates a df of low or high to include all ENSGIDs from vector made in previous line
ARTB_low <- dds_list_results_with_symbols$dds_ARTB_group_low[dds_list_results_with_symbols$dds_ARTB_group_low$ENSGID %in% ARTB_high_vs_low_ENSGID_combined, ]
ARTB_high <- dds_list_results_with_symbols$dds_ARTB_group_high[dds_list_results_with_symbols$dds_ARTB_group_high$ENSGID %in% ARTB_high_vs_low_ENSGID_combined, ]
ARTB_high_vs_low_either <- merge(ARTB_high, ARTB_low, by = "ENSGID")

combined_plot_ARTB_high_vs_low <- ggplot() +
      geom_point(data = ARTB_high_vs_low_either, aes(x = log2FoldChange.x, y = log2FoldChange.y)) + 
      geom_point(data = ARTB_high_vs_low_both, aes(x = log2FoldChange.x, y = log2FoldChange.y), color = "blue")

print(combined_plot_ARTB_high_vs_low)

ARTB_intersect_high_low <- subset(dds_list_results_with_symbols_05$dds_ARTB_group_high, ENSGID %in%  dds_list_results_with_symbols_05$dds_ARTB_group_low$ENSGID)

```

ARBT_group_high_2018_vs_ARBT_group_low_2018
```{r}

#plots for ATB group high vs low
ARTB_high2018_vs_low2018_both <- merge(dds_list_results_with_symbols_05$dds_ARTB_group_high_2018, dds_list_results_with_symbols_05$dds_ARTB_group_low_2018, by = "ENSGID")
#Creates a vector of all genes significant in both high/low striations
ARTB_high2018_vs_low2018_ENSGID_combined <- unique(c(dds_list_results_with_symbols_05$dds_ARTB_group_high_2018$ENSGID, dds_list_results_with_symbols_05$dds_ARTB_group_low_2018$ENSGID))
#Creates a df of low or high to include all ENSGIDs from vector made in previous line
ARTB_low2018 <- dds_list_results_with_symbols$dds_ARTB_group_low_2018[dds_list_results_with_symbols$dds_ARTB_group_low_2018$ENSGID %in% ARTB_high2018_vs_low2018_ENSGID_combined, ]
ARTB_high2018 <- dds_list_results_with_symbols$dds_ARTB_group_high_2018[dds_list_results_with_symbols$dds_ARTB_group_high_2018$ENSGID %in% ARTB_high2018_vs_low2018_ENSGID_combined, ]
ARTB_high2018_vs_low2018_either <- merge(ARTB_high2018, ARTB_low2018, by = "ENSGID")

combined_plot_ARTB_high2018_vs_low2018 <- ggplot() +
      geom_point(data = ARTB_high2018_vs_low2018_either, aes(x = log2FoldChange.x, y = log2FoldChange.y)) + 
      geom_point(data = ARTB_high2018_vs_low2018_both, aes(x = log2FoldChange.x, y = log2FoldChange.y), color = "blue")

print(combined_plot_ARTB_high2018_vs_low2018)

ARTB_intersect_high_low_2018 <- subset(dds_list_results_with_symbols_05$dds_ARTB_group_high_2018, ENSGID %in%  dds_list_results_with_symbols_05$dds_ARTB_group_low_2018$ENSGID)

```

ARBT_group_high_2021_vs_ARBT_group_low_2021
```{r}
#plots for ATB group high vs low
ARTB_high2021_vs_low2021_both <- merge(dds_list_results_with_symbols_05$dds_ARTB_group_high_2021, dds_list_results_with_symbols_05$dds_ARTB_group_low_2021, by = "ENSGID")
#Creates a vector of all genes significant in both high/low striations
ARTB_high2021_vs_low2021_ENSGID_combined <- unique(c(dds_list_results_with_symbols_05$dds_ARTB_group_high_2021$ENSGID, dds_list_results_with_symbols_05$dds_ARTB_group_low_2021$ENSGID))
#Creates a df of low or high to include all ENSGIDs from vector made in previous line
ARTB_low2021 <- dds_list_results_with_symbols$dds_ARTB_group_low_2021[dds_list_results_with_symbols$dds_ARTB_group_low_2021$ENSGID %in% ARTB_high2021_vs_low2021_ENSGID_combined, ]
ARTB_high2021 <- dds_list_results_with_symbols$dds_ARTB_group_high_2021[dds_list_results_with_symbols$dds_ARTB_group_high_2021$ENSGID %in% ARTB_high2021_vs_low2021_ENSGID_combined, ]
ARTB_high2021_vs_low2021_either <- merge(ARTB_high2021, ARTB_low2021, by = "ENSGID")

combined_plot_ARTB_high2021_vs_low2021 <- ggplot() +
      geom_point(data = ARTB_high2021_vs_low2021_either, aes(x = log2FoldChange.x, y = log2FoldChange.y)) + 
      geom_point(data = ARTB_high2021_vs_low2021_both, aes(x = log2FoldChange.x, y = log2FoldChange.y), color = "blue")

print(combined_plot_ARTB_high2021_vs_low2021)

ARTB_intersect_high_low_2021 <- subset(dds_list_results_with_symbols_05$dds_ARTB_group_high_2021, ENSGID %in%  dds_list_results_with_symbols_05$dds_ARTB_group_low_2021$ENSGID)

```

ARBT_2018_vs_ARBT_2021
```{r}
#plots for ATB group high vs low
ARTB_2018_vs_2021_both <- merge(dds_list_results_with_symbols_05$dds_ARTB_2018, dds_list_results_with_symbols_05$dds_ARTB_2021, by = "ENSGID")
#Creates a vector of all genes significant in both high/low striations
ARTB_2018_vs_2021_ENSGID_combined <- unique(c(dds_list_results_with_symbols_05$dds_ARTB_2018$ENSGID, dds_list_results_with_symbols_05$dds_ARTB_2021$ENSGID))
#Creates a df of low or high to include all ENSGIDs from vector made in previous line
ARTB_2018 <- dds_list_results_with_symbols$dds_ARTB_2018[dds_list_results_with_symbols$dds_ARTB_2018$ENSGID %in% ARTB_2018_vs_2021_ENSGID_combined, ]
ARTB_2021 <- dds_list_results_with_symbols$dds_ARTB_2021[dds_list_results_with_symbols$dds_ARTB_2021$ENSGID %in% ARTB_2018_vs_2021_ENSGID_combined, ]
ARTB_2018_vs_2021_either <- merge(ARTB_2018, ARTB_2021, by = "ENSGID")

combined_plot_ARTB_2018_vs_2021 <- ggplot() +
      geom_point(data = ARTB_2018_vs_2021_either, aes(x = log2FoldChange.x, y = log2FoldChange.y)) + 
      geom_point(data = ARTB_2018_vs_2021_both, aes(x = log2FoldChange.x, y = log2FoldChange.y), color = "blue")

print(combined_plot_ARTB_2018_vs_2021)

ARTB_intersect_2018_vs_2021 <- subset(dds_list_results_with_symbols_05$dds_ARTB_2018, ENSGID %in%  dds_list_results_with_symbols_05$dds_ARTB_2021$ENSGID)

```

ARBT_group_high_2018 vs ARBT_group_high_2021
#ARBT_group_low_2018 vs ARBT_group_low_2021      didn't do because 30 values in 2018 and 1 value in 2021
```{r}
#plots for ATB group high vs low
ARTB_high2018_vs_high2021_both <- merge(dds_list_results_with_symbols_05$dds_ARTB_group_high_2018, dds_list_results_with_symbols_05$dds_ARTB_group_high_2021, by = "ENSGID")
#Creates a vector of all genes significant in both high/low striations
ARTB_high2018_vs_high2021_ENSGID_combined <- unique(c(dds_list_results_with_symbols_05$dds_ARTB_group_high_2018$ENSGID, dds_list_results_with_symbols_05$dds_ARTB_group_high_2021$ENSGID))
#Creates a df of low or high to include all ENSGIDs from vector made in previous line
ARTB_high2018 <- dds_list_results_with_symbols$dds_ARTB_group_high_2018[dds_list_results_with_symbols$dds_ARTB_group_high_2018$ENSGID %in% ARTB_high2018_vs_high2021_ENSGID_combined, ]
ARTB_high2021 <- dds_list_results_with_symbols$dds_ARTB_group_high_2021[dds_list_results_with_symbols$dds_ARTB_group_high_2021$ENSGID %in% ARTB_high2018_vs_high2021_ENSGID_combined, ]
ARTB_high2018_vs_high2021_either <- merge(ARTB_high2018, ARTB_high2021, by = "ENSGID")

combined_plot_ARTB_high2021_vs_low2021 <- ggplot() +
      geom_point(data = ARTB_high2018_vs_high2021_either, aes(x = log2FoldChange.x, y = log2FoldChange.y)) + 
      geom_point(data = ARTB_high2018_vs_high2021_both, aes(x = log2FoldChange.x, y = log2FoldChange.y), color = "blue")

print(combined_plot_ARTB_high2021_vs_low2021)

ARTB_intersect_high_2018_vs_2021 <- subset(dds_list_results_with_symbols_05$dds_ARTB_group_high_2018, ENSGID %in%  dds_list_results_with_symbols_05$dds_ARTB_group_high_2018$ENSGID)


```


GSEA Prep 
```{r}
gsea_prep_05 <- lapply (
  dds_list_names,
  function(i) {
    sub_dds <- subset(dds_list_results_with_symbols_05[[i]], !(is.na(external_gene_name) | external_gene_name == ""), select = c(external_gene_name, log2FoldChange))
    #rownames(sub_dds) <- sub_dds$external_gene_name
  })
names(gsea_prep_05) <- dds_list_names

gsea_prep_10 <- lapply (
  dds_list_names,
  function(i) {
    sub_dds <- subset(dds_list_results_with_symbols_10[[i]], !(is.na(external_gene_name) | external_gene_name == ""), select = c(external_gene_name, log2FoldChange))
  })
names(gsea_prep_10) <- dds_list_names

gsea_prep_25 <- lapply (
  dds_list_names,
  function(i) {
    sub_dds <- subset(dds_list_results_with_symbols_25[[i]], !(is.na(external_gene_name) | external_gene_name == ""), select = c(external_gene_name, log2FoldChange))
  })
names(gsea_prep_25) <- dds_list_names


```















