---
title: Heatmaps
output: html_document
date: 
---

```{r}
categorical_deseq_results <- readRDS("/restricted/projectnb/cteseq/jrose/cte_deseq_output_cat_binary.rds")
continuous_deseq_results <- readRDS("/restricted/projectnb/cteseq/jrose/cte_deseq_output_cont.rds")
```

```{r, echo=FALSE}
library(DESeq2)
library(dplyr)
library(biomaRt)
library(tidyverse)
library(pheatmap)

all_deseq_obj <- c(continuous_deseq_results, categorical_deseq_results)
all_obj_names <- names(all_deseq_obj)
```
Heatmap prep @ 0.05
```{r}
#Obtain result from each deseq object
all_results <- lapply(
  all_obj_names,
  function(result_name) {
    results_c <- results(all_deseq_obj[[result_name]])
    results_c <- results_c[order(results_c$log2FoldChange), ]
    l2fc_genes_test <- data.frame(ENSGID = rownames(results_c), result_name = results_c$log2FoldChange)
    colnames(l2fc_genes_test)[2] <- result_name
    return(l2fc_genes_test)
    })
#assigns names to each result object
names(all_results) <- all_obj_names
#uses tidyverse to reduce list of DF to one, joining by ENSGID
results_combined <- all_results %>% reduce(full_join, by="ENSGID")
#assign rownames 
rownames(results_combined) <- results_combined$ENSGID
#removes ENSGID col
#results_combined <- results_combined[,-1]

#Making a gene map and assigning symbols to all_results
gene_ids <- unique(unlist(lapply(
  all_results,
  function(i)
    i$ENSGID
)))
#removes the dot and numbers after from all ensg IDs
cleaned_gene_ids <- sub("\\..*$", "", gene_ids)
#Creates a mart object for creating the gene map. If mirror needed, use:     , mirror = "useast"
ensembl.con <- useEnsembl(biomart = "genes", dataset = "hsapiens_gene_ensembl", mirror = "useast")

gene_map <- getBM(attributes = c("ensembl_gene_id", "external_gene_name"),
      filters = "ensembl_gene_id",
      values = cleaned_gene_ids,
      mart = ensembl.con)

#Get significant genes to base each heatmap on
all_results_sig_05 <- lapply(
  all_obj_names,
  function(result_name) {
    results_c <- results(all_deseq_obj[[result_name]])
    results_sig <- subset(results_c, padj < 0.05)
    results_sig <- results_sig[order(results_sig$pvalue), ]
    return(results_sig)
    })
names(all_results_sig_05) <- all_obj_names  

heatmap_list <- lapply(
  all_obj_names,
  function(design_factor) {
    design_res <- all_results_sig_05[[design_factor]]
    design_df <- data.frame(design_res)
    design_genes <- data.frame(ENSGID = rownames(design_df), design_factor = design_df$log2FoldChange)
    merged_values <- merge(results_combined, design_genes, by="ENSGID")
    rownames(merged_values) <- merged_values[,"ENSGID"]
    merged_values <- subset(merged_values, select = -design_factor)
    merged_values <- subset(merged_values, select = -ENSGID)
  })
names(heatmap_list) <- all_obj_names 

#Removes dots in ENSGID IDs
for (i in all_obj_names) {
  rownames(heatmap_list[[i]]) <- gsub("\\.\\d+$", "", rownames(heatmap_list[[i]]))
}
#Converts ENSGIDs to gene symbols using map
for (i in seq_along(heatmap_list)) {
  heatmap_list[[i]]$rownames <- rownames(heatmap_list[[i]])
  heatmap_list[[i]] <- merge(heatmap_list[[i]], gene_map, by.x ="rownames", by.y ="ensembl_gene_id", all.x = TRUE)
  heatmap_list[[i]] <- heatmap_list[[i]][complete.cases(heatmap_list[[i]]$external_gene_name) & heatmap_list[[i]]$external_gene_name != "", ]
  rownames(heatmap_list[[i]]) <- make.unique(as.character(heatmap_list[[i]]$external_gene_name))
  heatmap_list[[i]] <- subset(heatmap_list[[i]], select = -c( rownames, external_gene_name))
}

for (i in seq_along(heatmap_list)){
  heatmap_list <- Filter(function(i) nrow(i) > 1, heatmap_list)
}
filtered_names <- names(heatmap_list)
```
Heatmap prep @ 0.10
```{r}
all_results_sig_10 <- lapply(
  all_obj_names,
  function(result_name) {
    results_c <- results(all_deseq_obj[[result_name]])
    results_sig <- subset(results_c, padj < 0.10)
    results_sig <- results_sig[order(results_sig$pvalue), ]
    return(results_sig)
    })
names(all_results_sig_10) <- all_obj_names  

heatmap_list_10 <- lapply(
  all_obj_names,
  function(design_factor) {
    design_res <- all_results_sig_10[[design_factor]]
    design_df <- data.frame(design_res)
    design_genes <- data.frame(ENSGID = rownames(design_df), design_factor = design_df$log2FoldChange)
    merged_values <- merge(results_combined, design_genes, by="ENSGID")
    rownames(merged_values) <- merged_values[,"ENSGID"]
    merged_values <- subset(merged_values, select = -design_factor)
    merged_values <- subset(merged_values, select = -ENSGID)
  })
names(heatmap_list_10) <- all_obj_names 

#Removes dots in ENSGID IDs
for (i in all_obj_names) {
  rownames(heatmap_list_10[[i]]) <- gsub("\\.\\d+$", "", rownames(heatmap_list_10[[i]]))
}
#Converts ENSGIDs to gene symbols using map
for (i in seq_along(heatmap_list_10)) {
  heatmap_list_10[[i]]$rownames <- rownames(heatmap_list_10[[i]])
  heatmap_list_10[[i]] <- merge(heatmap_list_10[[i]], gene_map, by.x ="rownames", by.y ="ensembl_gene_id", all.x = TRUE)
  heatmap_list_10[[i]] <- heatmap_list_10[[i]][complete.cases(heatmap_list_10[[i]]$external_gene_name) & heatmap_list_10[[i]]$external_gene_name != "", ]
  rownames(heatmap_list_10[[i]]) <- make.unique(as.character(heatmap_list_10[[i]]$external_gene_name))
  heatmap_list_10[[i]] <- subset(heatmap_list_10[[i]], select = -c( rownames, external_gene_name))
}

for (i in seq_along(heatmap_list_10)){
  heatmap_list_10 <- Filter(function(i) nrow(i) > 1, heatmap_list_10)
}
filtered_names <- names(heatmap_list_10)

```
Heamtap prep @ 0.01
```{r}
all_results_sig_01 <- lapply(
  all_obj_names,
  function(result_name) {
    results_c <- results(all_deseq_obj[[result_name]])
    results_sig <- subset(results_c, padj < 0.01)
    results_sig <- results_sig[order(results_sig$pvalue), ]
    return(results_sig)
    })
names(all_results_sig_01) <- all_obj_names  

heatmap_list_01 <- lapply(
  all_obj_names,
  function(design_factor) {
    design_res <- all_results_sig_01[[design_factor]]
    design_df <- data.frame(design_res)
    design_genes <- data.frame(ENSGID = rownames(design_df), design_factor = design_df$log2FoldChange)
    merged_values <- merge(results_combined, design_genes, by="ENSGID")
    rownames(merged_values) <- merged_values[,"ENSGID"]
    merged_values <- subset(merged_values, select = -design_factor)
    merged_values <- subset(merged_values, select = -ENSGID)
  })
names(heatmap_list_01) <- all_obj_names 

#Removes dots in ENSGID IDs
for (i in all_obj_names) {
  rownames(heatmap_list_01[[i]]) <- gsub("\\.\\d+$", "", rownames(heatmap_list_01[[i]]))
}
#Converts ENSGIDs to gene symbols using map
for (i in seq_along(heatmap_list_01)) {
  heatmap_list_01[[i]]$rownames <- rownames(heatmap_list_01[[i]])
  heatmap_list_01[[i]] <- merge(heatmap_list_01[[i]], gene_map, by.x ="rownames", by.y ="ensembl_gene_id", all.x = TRUE)
  heatmap_list_01[[i]] <- heatmap_list_01[[i]][complete.cases(heatmap_list_01[[i]]$external_gene_name) & heatmap_list_01[[i]]$external_gene_name != "", ]
  rownames(heatmap_list_01[[i]]) <- make.unique(as.character(heatmap_list_01[[i]]$external_gene_name))
  heatmap_list_01[[i]] <- subset(heatmap_list_01[[i]], select = -c( rownames, external_gene_name))
}

for (i in seq_along(heatmap_list_01)){
  heatmap_list_01 <- Filter(function(i) nrow(i) > 1, heatmap_list_01)
}
filtered_names <- names(heatmap_list_01)
```
clustered heatmaps @ 0.05
```{r}
for (i in filtered_names) {
  palette_length <- 50
  colors <- colorRampPalette(c("blue", "white", "red"))(palette_length)
  #initializing factor result dataframe
  scaled_05 <- heatmap_list[[i]]
  #divides each column's values by the max ABS of the column that value is under. 
  for (x in seq_along(scaled_05)) {
    scaled_05[[x]] <- scaled_05[[x]] / max(abs(scaled_05[[x]]))
  }
  #Sets breaks to give a consistent -1 to 1 range and center zeros 
  hm_breaks <- c(seq(min(scaled_05), 0, length.out=ceiling(palette_length/2) +1), 
              seq(max(scaled_05)/palette_length, max(scaled_05), length.out=floor(palette_length/2)))
  pheatmap(scaled_05, cluster_rows = TRUE, cluster_cols = TRUE, color = colors, breaks = hm_breaks, main = paste("Heatmap of significant (0.05) genes from ", i))
}
```

```{r}
for (i in filtered_names) {
  palette_length <- 50
  colors <- colorRampPalette(c("blue", "white", "red"))(palette_length)
  hm_breaks <- c(seq(min(heatmap_list[[i]]), 0, length.out=ceiling(palette_length/2) +1), 
              seq(max(heatmap_list[[i]])/palette_length, max(heatmap_list[[i]]), length.out=floor(palette_length/2)))
  pheatmap(heatmap_list[[i]], cluster_rows = TRUE, cluster_cols = TRUE, color = colors, breaks = hm_breaks, main = paste("Heatmap of significant (0.05) genes from ", i))
}
```

clustered heatmaps @ 0.10
```{r}
for (i in filtered_names) {
  palette_length <- 50
  colors <- colorRampPalette(c("blue", "white", "red"))(palette_length)
  #initializing factor result dataframe
  scaled_10 <- heatmap_list[[i]]
  #divides each column's values by the max ABS of the column that value is under. 
  for (x in seq_along(scaled_10)) {
    scaled_10[[x]] <- scaled_10[[x]] / max(abs(scaled_10[[x]]))
  }
  hm_breaks <- c(seq(min(scaled_10), 0, length.out=ceiling(palette_length/2) +1), 
              seq(max(scaled_10)/palette_length, max(scaled_10), length.out=floor(palette_length/2)))

  pheatmap(scaled_10, cluster_rows = TRUE, cluster_cols = TRUE, color = colors, breaks = hm_breaks, main = paste("Heatmap of significant (0.10) genes from ", i))
}
```
clustered heatmaps @ 0.01
```{r}
for (i in filtered_names) {
  palette_length <- 50
  colors <- colorRampPalette(c("blue", "white", "red"))(palette_length)
  #initializing factor result dataframe
  scaled_01 <- heatmap_list[[i]]
  #divides each column's values by the max ABS of the column that value is under. 
  for (x in seq_along(scaled_01)) {
    scaled_01[[x]] <- scaled_01[[x]] / max(abs(scaled_01[[x]]))
  }
  hm_breaks <- c(seq(min(scaled_01), 0, length.out=ceiling(palette_length/2) +1), 
              seq(max(scaled_01)/palette_length, max(scaled_01), length.out=floor(palette_length/2)))

  pheatmap(scaled_01, cluster_rows = TRUE, cluster_cols = TRUE, color = colors, breaks = hm_breaks, main = paste("Heatmap of significant (0.01) genes from ", i))
}
```
